---
title: "Introduction to the dcsbm package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to the dcsbm package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
devtools::load_all()
set.seed(2022)
```


```{r, eval=FALSE}
library(dcsbm)
```


### A. Agglomerative Merge

#### 1. No degree correction

```{r}
G <- sample_ppm(100, 0.9, 10, 3, directed = TRUE, loops = TRUE)

model <- dcsbm(G, n.sweeps = 1, verbose = FALSE)
 
plot(G, vertex.color = model$best_partition, vertex.label = NA)
```


#### 2. With degree correction

```{r}
G <- sample_dcppm(100, 0.9, 10, 3, k_coef = 2, directed = TRUE, loops = TRUE)

model <- dcsbm(G, degree_correction = TRUE, n.sweeps = 5, verbose = FALSE)
 
plot(G, vertex.color = model$best_partition, vertex.label = NA, sub = "Best partition")
plot(G, vertex.color = c(rep(1,34), rep(2,33), rep(3,33)), vertex.label = NA, sub = "True partition")
```
